//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_Monitor.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IMonitor")]
    public interface IMonitor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitor/GetRequestToVelib", ReplyAction="http://tempuri.org/IMonitor/GetRequestToVelibResponse")]
        string GetRequestToVelib(string startTime, string endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitor/GetRequestToVelib", ReplyAction="http://tempuri.org/IMonitor/GetRequestToVelibResponse")]
        System.Threading.Tasks.Task<string> GetRequestToVelibAsync(string startTime, string endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitor/GetTheNumberOfClient", ReplyAction="http://tempuri.org/IMonitor/GetTheNumberOfClientResponse")]
        string GetTheNumberOfClient(string startTime, string endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitor/GetTheNumberOfClient", ReplyAction="http://tempuri.org/IMonitor/GetTheNumberOfClientResponse")]
        System.Threading.Tasks.Task<string> GetTheNumberOfClientAsync(string startTime, string endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitor/GetRequestOfClient", ReplyAction="http://tempuri.org/IMonitor/GetRequestOfClientResponse")]
        string GetRequestOfClient(string startTime, string endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitor/GetRequestOfClient", ReplyAction="http://tempuri.org/IMonitor/GetRequestOfClientResponse")]
        System.Threading.Tasks.Task<string> GetRequestOfClientAsync(string startTime, string endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitor/GetCacheNumber", ReplyAction="http://tempuri.org/IMonitor/GetCacheNumberResponse")]
        int GetCacheNumber();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitor/GetCacheNumber", ReplyAction="http://tempuri.org/IMonitor/GetCacheNumberResponse")]
        System.Threading.Tasks.Task<int> GetCacheNumberAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitor/GetAverageDelay", ReplyAction="http://tempuri.org/IMonitor/GetAverageDelayResponse")]
        string GetAverageDelay();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitor/GetAverageDelay", ReplyAction="http://tempuri.org/IMonitor/GetAverageDelayResponse")]
        System.Threading.Tasks.Task<string> GetAverageDelayAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMonitorChannel : Admin_Monitor.ServiceReference1.IMonitor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MonitorClient : System.ServiceModel.ClientBase<Admin_Monitor.ServiceReference1.IMonitor>, Admin_Monitor.ServiceReference1.IMonitor {
        
        public MonitorClient() {
        }
        
        public MonitorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MonitorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonitorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonitorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetRequestToVelib(string startTime, string endTime) {
            return base.Channel.GetRequestToVelib(startTime, endTime);
        }
        
        public System.Threading.Tasks.Task<string> GetRequestToVelibAsync(string startTime, string endTime) {
            return base.Channel.GetRequestToVelibAsync(startTime, endTime);
        }
        
        public string GetTheNumberOfClient(string startTime, string endTime) {
            return base.Channel.GetTheNumberOfClient(startTime, endTime);
        }
        
        public System.Threading.Tasks.Task<string> GetTheNumberOfClientAsync(string startTime, string endTime) {
            return base.Channel.GetTheNumberOfClientAsync(startTime, endTime);
        }
        
        public string GetRequestOfClient(string startTime, string endTime) {
            return base.Channel.GetRequestOfClient(startTime, endTime);
        }
        
        public System.Threading.Tasks.Task<string> GetRequestOfClientAsync(string startTime, string endTime) {
            return base.Channel.GetRequestOfClientAsync(startTime, endTime);
        }
        
        public int GetCacheNumber() {
            return base.Channel.GetCacheNumber();
        }
        
        public System.Threading.Tasks.Task<int> GetCacheNumberAsync() {
            return base.Channel.GetCacheNumberAsync();
        }
        
        public string GetAverageDelay() {
            return base.Channel.GetAverageDelay();
        }
        
        public System.Threading.Tasks.Task<string> GetAverageDelayAsync() {
            return base.Channel.GetAverageDelayAsync();
        }
    }
}
