//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_GUI.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IGoogleMapService")]
    public interface IGoogleMapService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGoogleMapService/GetRoute", ReplyAction="http://tempuri.org/IGoogleMapService/GetRouteResponse")]
        string[] GetRoute(string city, string origin, string destination);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGoogleMapService/GetRoute", ReplyAction="http://tempuri.org/IGoogleMapService/GetRouteResponse")]
        System.Threading.Tasks.Task<string[]> GetRouteAsync(string city, string origin, string destination);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGoogleMapServiceChannel : Client_GUI.ServiceReference2.IGoogleMapService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GoogleMapServiceClient : System.ServiceModel.ClientBase<Client_GUI.ServiceReference2.IGoogleMapService>, Client_GUI.ServiceReference2.IGoogleMapService {
        
        public GoogleMapServiceClient() {
        }
        
        public GoogleMapServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GoogleMapServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GoogleMapServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GoogleMapServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetRoute(string city, string origin, string destination) {
            return base.Channel.GetRoute(city, origin, destination);
        }
        
        public System.Threading.Tasks.Task<string[]> GetRouteAsync(string city, string origin, string destination) {
            return base.Channel.GetRouteAsync(city, origin, destination);
        }
    }
}
